language: python
dist: xenial
python:
  - 3.7
install:
  - pip install -e .
  - pip install -r requirements.txt 
script:
  - py.test --cov . --cov-report xml:coverage.xml

env:
  global:
    - CC_TEST_REPORTER_ID=

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
